version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "3001:8000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
